const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2348036399544";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_17_20_08_31_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjA4LFxuICAgICAgICAxNzEsXG4gICAgICAgIDksXG4gICAgICAgIDIzOCxcbiAgICAgICAgODcsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTQ4LFxuICAgICAgICAyNSxcbiAgICAgICAgMzAsXG4gICAgICAgIDE4OSxcbiAgICAgICAgNjcsXG4gICAgICAgIDUsXG4gICAgICAgIDEyLFxuICAgICAgICAzLFxuICAgICAgICAxNDYsXG4gICAgICAgIDc4LFxuICAgICAgICAxOSxcbiAgICAgICAgMTcsXG4gICAgICAgIDY1LFxuICAgICAgICAxMTUsXG4gICAgICAgIDk4LFxuICAgICAgICAyMzAsXG4gICAgICAgIDE2MixcbiAgICAgICAgMjI3LFxuICAgICAgICA0NyxcbiAgICAgICAgMTc2LFxuICAgICAgICAxNTYsXG4gICAgICAgIDYsXG4gICAgICAgIDY3LFxuICAgICAgICAyNTQsXG4gICAgICAgIDg1LFxuICAgICAgICA4OFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNTQsXG4gICAgICAgIDExOSxcbiAgICAgICAgMTQzLFxuICAgICAgICAyMTYsXG4gICAgICAgIDE1NCxcbiAgICAgICAgODEsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTI0LFxuICAgICAgICAyMzEsXG4gICAgICAgIDIwMSxcbiAgICAgICAgMjM3LFxuICAgICAgICA5MCxcbiAgICAgICAgMjA4LFxuICAgICAgICAxNTMsXG4gICAgICAgIDIyMixcbiAgICAgICAgNzcsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjM2LFxuICAgICAgICAyMTQsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMjAyLFxuICAgICAgICA0MCxcbiAgICAgICAgNDYsXG4gICAgICAgIDY4LFxuICAgICAgICA1LFxuICAgICAgICA5NCxcbiAgICAgICAgNTIsXG4gICAgICAgIDI4LFxuICAgICAgICAyNCxcbiAgICAgICAgNTgsXG4gICAgICAgIDc3LFxuICAgICAgICA2OVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNjQsXG4gICAgICAgIDE1NCxcbiAgICAgICAgOTcsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMzIsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTQyLFxuICAgICAgICA4OCxcbiAgICAgICAgMjQwLFxuICAgICAgICAyNyxcbiAgICAgICAgNyxcbiAgICAgICAgMTQsXG4gICAgICAgIDEwNCxcbiAgICAgICAgNCxcbiAgICAgICAgMjE1LFxuICAgICAgICAyNTUsXG4gICAgICAgIDczLFxuICAgICAgICAyMDQsXG4gICAgICAgIDIxNixcbiAgICAgICAgNjMsXG4gICAgICAgIDQ2LFxuICAgICAgICA5OCxcbiAgICAgICAgNjcsXG4gICAgICAgIDcwLFxuICAgICAgICA2LFxuICAgICAgICAyMzEsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTk4LFxuICAgICAgICA0NCxcbiAgICAgICAgNzAsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTIyXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTEsXG4gICAgICAgIDEwNixcbiAgICAgICAgMjIwLFxuICAgICAgICAyMDYsXG4gICAgICAgIDI0LFxuICAgICAgICAyNDYsXG4gICAgICAgIDg5LFxuICAgICAgICAwLFxuICAgICAgICA0NixcbiAgICAgICAgODMsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMTk0LFxuICAgICAgICA3MixcbiAgICAgICAgMjcsXG4gICAgICAgIDYwLFxuICAgICAgICAyMjEsXG4gICAgICAgIDE4NixcbiAgICAgICAgNDYsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMjE4LFxuICAgICAgICAyMDgsXG4gICAgICAgIDE1LFxuICAgICAgICAxNixcbiAgICAgICAgNixcbiAgICAgICAgMjE2LFxuICAgICAgICAxNDgsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTUyLFxuICAgICAgICAxNjUsXG4gICAgICAgIDkxLFxuICAgICAgICA1NVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTYsXG4gICAgICAgIDI1NCxcbiAgICAgICAgODQsXG4gICAgICAgIDEyLFxuICAgICAgICA1NyxcbiAgICAgICAgMjA0LFxuICAgICAgICAxNTQsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMjQxLFxuICAgICAgICAxODIsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTI1LFxuICAgICAgICAxNjMsXG4gICAgICAgIDEzLFxuICAgICAgICA1OCxcbiAgICAgICAgMTAyLFxuICAgICAgICAyNixcbiAgICAgICAgMTIzLFxuICAgICAgICAzNixcbiAgICAgICAgOTQsXG4gICAgICAgIDIxMCxcbiAgICAgICAgNTMsXG4gICAgICAgIDQ2LFxuICAgICAgICAxMjEsXG4gICAgICAgIDM2LFxuICAgICAgICAxMzQsXG4gICAgICAgIDMyLFxuICAgICAgICAxOTksXG4gICAgICAgIDU4LFxuICAgICAgICAyNDAsXG4gICAgICAgIDIzMSxcbiAgICAgICAgNjhcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNixcbiAgICAgICAgNTIsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMjM1LFxuICAgICAgICAxMDcsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMTQ0LFxuICAgICAgICAxMDQsXG4gICAgICAgIDE4NixcbiAgICAgICAgMjExLFxuICAgICAgICA0MCxcbiAgICAgICAgMTg2LFxuICAgICAgICAyMTMsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMjM5LFxuICAgICAgICAyMzcsXG4gICAgICAgIDE4NCxcbiAgICAgICAgNSxcbiAgICAgICAgMTQzLFxuICAgICAgICAxMTEsXG4gICAgICAgIDAsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTIxLFxuICAgICAgICAxODgsXG4gICAgICAgIDkyLFxuICAgICAgICAxMjEsXG4gICAgICAgIDcyLFxuICAgICAgICA3OCxcbiAgICAgICAgMTc5LFxuICAgICAgICA0NSxcbiAgICAgICAgMTQ0LFxuICAgICAgICA4MFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA0MCxcbiAgICAgICAgICA2MixcbiAgICAgICAgICA5MixcbiAgICAgICAgICA1LFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgOTUsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDIwNyxcbiAgICAgICAgICAxMjUsXG4gICAgICAgICAgMTg4LFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICA5MSxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDU0LFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgMSxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDIwNCxcbiAgICAgICAgICA4OFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDYsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICA1MixcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAxNDksXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDk5LFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDE4NyxcbiAgICAgICAgICA5MyxcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDIxMCxcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDEyMixcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMjI1LFxuICAgICAgICAgIDk3XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTE4LFxuICAgICAgICA2MyxcbiAgICAgICAgMTEsXG4gICAgICAgIDc1LFxuICAgICAgICAxOTgsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTQ0LFxuICAgICAgICA1NSxcbiAgICAgICAgMjQ4LFxuICAgICAgICA0MCxcbiAgICAgICAgMjM5LFxuICAgICAgICAxNzYsXG4gICAgICAgIDIwMSxcbiAgICAgICAgODMsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMixcbiAgICAgICAgMTksXG4gICAgICAgIDEyNixcbiAgICAgICAgNzksXG4gICAgICAgIDEzNixcbiAgICAgICAgMTc1LFxuICAgICAgICA2NyxcbiAgICAgICAgMjA2LFxuICAgICAgICAxMTQsXG4gICAgICAgIDI0MixcbiAgICAgICAgMTc0LFxuICAgICAgICAzNixcbiAgICAgICAgMTY3LFxuICAgICAgICAxMixcbiAgICAgICAgMTM2LFxuICAgICAgICA2MixcbiAgICAgICAgNTMsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTUsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjA2LFxuICAgICAgICAxMjgsXG4gICAgICAgIDgxLFxuICAgICAgICAxNCxcbiAgICAgICAgMTAzLFxuICAgICAgICAxNDYsXG4gICAgICAgIDc4LFxuICAgICAgICAxMTIsXG4gICAgICAgIDkyLFxuICAgICAgICAxODAsXG4gICAgICAgIDgwLFxuICAgICAgICAyMTMsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMzEsXG4gICAgICAgIDE5MSxcbiAgICAgICAgOTUsXG4gICAgICAgIDc0LFxuICAgICAgICAyMTYsXG4gICAgICAgIDIzLFxuICAgICAgICA5OSxcbiAgICAgICAgMjUzLFxuICAgICAgICAyMDUsXG4gICAgICAgIDU4LFxuICAgICAgICAxNjQsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTcsXG4gICAgICAgIDE1NCxcbiAgICAgICAgNyxcbiAgICAgICAgMTM2XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxNTksXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiV2dwcHRHSVNtS3NIRS9iSXRTeVNkNXlubm1ZUm1XNGV3THZxMCsxVWM0OD1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ4MDM2Mzk5NTQ0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJBRDBCRDQ3QTVFNTRDQTk5M0FDREI3ODBENTBFRDdDNFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjUxMjQ4MDRcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiTW1zY2dGQllUai1YOGNfV2EwRDFVUVwiLFxuICBcInBob25lSWRcIjogXCI3NDk5NmEzNC04MjViLTRmYmYtOTVjNi04YTM5ZmZmYjYzYWVcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNzAsXG4gICAgICA4NCxcbiAgICAgIDc1LFxuICAgICAgMjA2LFxuICAgICAgMTcyLFxuICAgICAgOTIsXG4gICAgICAxMjUsXG4gICAgICAzOSxcbiAgICAgIDIzNSxcbiAgICAgIDg4LFxuICAgICAgMTM4LFxuICAgICAgMTY4LFxuICAgICAgMTMwLFxuICAgICAgNixcbiAgICAgIDE5NixcbiAgICAgIDIyOCxcbiAgICAgIDUzLFxuICAgICAgMTc5LFxuICAgICAgNzgsXG4gICAgICAxOThcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjYsXG4gICAgICAyMDIsXG4gICAgICAxODksXG4gICAgICAxMjgsXG4gICAgICAxODIsXG4gICAgICAzMyxcbiAgICAgIDE4NSxcbiAgICAgIDgxLFxuICAgICAgNDksXG4gICAgICAxMzcsXG4gICAgICA0MCxcbiAgICAgIDcyLFxuICAgICAgMTQ4LFxuICAgICAgMTE5LFxuICAgICAgMTY1LFxuICAgICAgMTQxLFxuICAgICAgMTY2LFxuICAgICAgMjMxLFxuICAgICAgOTgsXG4gICAgICAxNzdcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiVzZQU0dKVDJcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDgwMzYzOTk1NDQ6MTZAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJPTFVGSVNBWU8gT0xPWUVERSBESVZJTkUgU09OR1MgTUlOSVNUUllcIixcbiAgICBcImxpZFwiOiBcIjIzMjQwMjUyNTg4MjA5OjE2QGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ016WXorOERFTHFoemJZR0dBUWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiU3FJa0FMbExwSkRrak41Vjc4M2hqaUp4bEtPdzlRb043RGN6UFV6dnpqaz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJwbmEwVFErQ1ZqaTI0RjJJTHFCVzM0UDFGa1VoTHhhVEphVnl2dnFXQWcrd3F5aExwNEJJQS8xdnNVS1JadHFmMnZwR01rR3BmQkk1NWEwajFwalJCUT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCIyMTJSYUZ2YmF4Q3MyUWZraVJJVDZ3UjNUM1RuUStiOXFFMzBSdWNyZTBKZlp5aU0rYndGQ2NTbmJwL3B6WjdyN2JCMFBML1QrcVF3MVhNK3VKQXFoUT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzQ4MDM2Mzk5NTQ0OjE2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDM2LFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMTg1LFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDE2NCxcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDE0MCxcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgODUsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDIwNSxcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMTYzLFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMTAsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMjM2LFxuICAgICAgICAgIDU1LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICAyMDYsXG4gICAgICAgICAgNTdcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcInNtYmFcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyNTEyNDc5OCxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQVBWalwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUFZqLmpzb24iOiAie1wia2V5RGF0YVwiOlwiTHVRRlJpVmxCenozTUxHS25XS2xhWS8xbXI1Sld1bjVHMndXcXE4dW9jST1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMDM5Mzk1OTE2LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
